# Generated by Django 3.1.6 on 2021-06-06 02:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='get_following_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
