# Generated by Django 3.1.6 on 2021-06-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
