# Generated by Django 3.1.6 on 2021-08-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20210808_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=280, null=True),
        ),
    ]
